### ISSUE TITLE
Feedback homework JS2 Week 3

### ISSUE THREAD

**Issue by remarcmij** [mahmutkaya/hyf-javascript2#3]
Hi Mahmut, here is my feedback on your homework.

## Step 4.1

OK

## Step 4.2

Ok, but you don't have to reconfirm that a number is divisible by both 3 and 5 because the preceding console.log statements already tell that.

## Other steps

All other homework is missing.

**Comment by mahmutkaya** [comment]
Hi Jim, I fixed and completed.. Thanks for feedback.
